services:
  backend:
    build: ./backend
    container_name: aicourse-backend
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - neo4j
    environment:
      - DATABASE_URL=mysql+pymysql://root:root@mysql:3306/aicourse
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASS=aicourse
    volumes:
      - ./data/uploads:/data/uploads
      - ./data/chroma:/data/chroma
      - ./hf_models:/data/hf_models

  frontend:
    build: ./frontend
    container_name: aicourse-frontend
    ports:
      - ":80:80"
    depends_on:
      - backend

  mysql:
    image: mysql:8.0
    container_name: aicourse-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aicourse
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql

  neo4j:
    image: neo4j:5.13
    container_name: aicourse-neo4j
    restart: always
    environment:
      NEO4J_AUTH: "neo4j/aicourse"
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./data/neo4j:/data

